client:
  image: node:8
  working_dir: /src
  environment:
    FAKTORY_URL: server:7419
  links:
    - server
  volumes:
    - .:/src
server:
  image: contribsys/faktory:0.5.0
  command: ["-b", "0.0.0.0:7419", "-no-tls"]
  ports:
    - "7420:7420"
    - "7419:7419"
